server:
  port: 8090

spring:
  application:
    name: order-microservice

  docker:
    compose:
      lifecycle-management: start_only
      file: src/main/docker/compose.yaml
      enabled: true
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka